### PR TITLE
Update Version of Ramda

### PR DESCRIPTION
**Pull request by JasonSooter**
The current version of Ramda is 0.25.0.

### CODE REVIEW

**Comment by rjhilgefort** [comment]
Would love to be able to install this straight out of Dash. @alexbepple Any chance of this getting merged and pushed out through whatever process required to have it in the Dash app?

**Comment by rjhilgefort** [comment]
@functionalStoic I attempted to do a local build with this change and it fails. doesn't look like `0.25.0` is coming down from `ramdajs.com`. Were you able to get this built locally?

**Comment by JasonSooter** [comment]
@rjhilgefort I was not able to either. I have since switched over to devdocs.io. Good Luck!

**Comment by rjhilgefort** [comment]
@functionalStoic giving up or is this done now?

**Comment by JasonSooter** [comment]
@rjhilgefort Giving up. Cleaning up the PRs that show up when clicking on the "Pull requests" link in the header bar

**Pull request closed without merging**
